import { computed } from 'vue'
import { useCampaignStore } from '@/stores/campaign'

// Per-system feature flags — controls which mechanics are visible in the UI.
const SYSTEM_FEATURES = {
  dnd5e: {
    hasStress: false, hasSanity: false,
    usesXP: false, usesMilestone: true,
    hasDndBeyond: true, hasBuiltinSheet: false,
    maxLevel: 20,
    sheetLabel: 'D&D Beyond',
  },
  coc: {
    hasStress: false, hasSanity: true,
    usesXP: true, usesMilestone: false,
    hasDndBeyond: false, hasBuiltinSheet: true,
    hasMagicPoints: true,
    maxLevel: 10,
    sheetLabel: 'Investigator Sheet',
    coreStats: [
      { key: 'str', label: 'STR' }, { key: 'con', label: 'CON' },
      { key: 'siz', label: 'SIZ' }, { key: 'dex', label: 'DEX' },
      { key: 'app', label: 'APP' }, { key: 'edu', label: 'EDU' },
      { key: 'int', label: 'INT' }, { key: 'pow', label: 'POW' },
      { key: 'luck', label: 'Luck' },
    ],
    extraFields: [
      { key: 'age',          label: 'Age',                type: 'number'  },
      { key: 'birthplace',   label: 'Birthplace',         type: 'text'    },
      { key: 'pronoun',      label: 'Pronoun',            type: 'text'    },
      { key: 'residence',    label: 'Residence',          type: 'text'    },
      { key: 'assets',       label: 'Assets',             type: 'text'    },
      { key: 'gear',         label: 'Gear & Possessions', type: 'textarea'},
      { key: 'major_wound',  label: 'Major Wound',        type: 'boolean' },
      { key: 'temp_insanity',label: 'Temporary Insanity', type: 'boolean' },
      { key: 'indef_insanity',label:'Indefinite Insanity',type: 'boolean' },
    ],
    systemSkills: [
      { key: 'sk_accounting',    label: 'Accounting',           base: 5  },
      { key: 'sk_anthropology',  label: 'Anthropology',         base: 1  },
      { key: 'sk_appraise',      label: 'Appraise',             base: 5  },
      { key: 'sk_archaeology',   label: 'Archaeology',          base: 1  },
      { key: 'sk_art',           label: 'Art/Craft',            base: 5  },
      { key: 'sk_charm',         label: 'Charm',                base: 15 },
      { key: 'sk_climb',         label: 'Climb',                base: 20 },
      { key: 'sk_credit',        label: 'Credit Rating',        base: 0  },
      { key: 'sk_cthulhu',       label: 'Cthulhu Mythos',       base: 0  },
      { key: 'sk_disguise',      label: 'Disguise',             base: 5  },
      { key: 'sk_dodge',         label: 'Dodge',                base: 0, note: 'DEX×2' },
      { key: 'sk_drive',         label: 'Drive Auto',           base: 20 },
      { key: 'sk_elec_repair',   label: 'Elec. Repair',         base: 10 },
      { key: 'sk_fast_talk',     label: 'Fast Talk',            base: 5  },
      { key: 'sk_fighting',      label: 'Fighting (Brawl)',     base: 25 },
      { key: 'sk_firearms_h',    label: 'Firearms (Handgun)',   base: 20 },
      { key: 'sk_firearms_r',    label: 'Firearms (Rifle/SG)',  base: 25 },
      { key: 'sk_first_aid',     label: 'First Aid',            base: 30 },
      { key: 'sk_history',       label: 'History',              base: 5  },
      { key: 'sk_intimidate',    label: 'Intimidate',           base: 15 },
      { key: 'sk_jump',          label: 'Jump',                 base: 20 },
      { key: 'sk_language',      label: 'Language (Other)',     base: 1  },
      { key: 'sk_law',           label: 'Law',                  base: 5  },
      { key: 'sk_library',       label: 'Library Use',          base: 20 },
      { key: 'sk_listen',        label: 'Listen',               base: 20 },
      { key: 'sk_locksmith',     label: 'Locksmith',            base: 1  },
      { key: 'sk_mech_repair',   label: 'Mech. Repair',         base: 10 },
      { key: 'sk_medicine',      label: 'Medicine',             base: 1  },
      { key: 'sk_natural',       label: 'Natural World',        base: 10 },
      { key: 'sk_navigate',      label: 'Navigate',             base: 10 },
      { key: 'sk_occult',        label: 'Occult',               base: 5  },
      { key: 'sk_operate',       label: 'Op. Hvy. Mach.',       base: 1  },
      { key: 'sk_persuade',      label: 'Persuade',             base: 10 },
      { key: 'sk_pilot',         label: 'Pilot',                base: 1  },
      { key: 'sk_psychology',    label: 'Psychology',           base: 10 },
      { key: 'sk_psychoanalysis',label: 'Psychoanalysis',       base: 1  },
      { key: 'sk_ride',          label: 'Ride',                 base: 5  },
      { key: 'sk_science',       label: 'Science',              base: 1  },
      { key: 'sk_sleight',       label: 'Sleight of Hand',      base: 10 },
      { key: 'sk_spot',          label: 'Spot Hidden',          base: 25 },
      { key: 'sk_stealth',       label: 'Stealth',              base: 20 },
      { key: 'sk_survival',      label: 'Survival',             base: 10 },
      { key: 'sk_swim',          label: 'Swim',                 base: 20 },
      { key: 'sk_throw',         label: 'Throw',                base: 20 },
      { key: 'sk_track',         label: 'Track',                base: 10 },
    ],
  },
  alien: {
    hasStress: true, hasSanity: false,
    usesXP: true, usesMilestone: false,
    hasDndBeyond: false, hasBuiltinSheet: true,
    hasConditions: true,
    hasRadiation: true,
    maxLevel: 5,
    sheetLabel: 'Character Sheet',
    coreStats: [
      { key: 'strength', label: 'Strength' }, { key: 'agility', label: 'Agility' },
      { key: 'wits',     label: 'Wits'     }, { key: 'empathy', label: 'Empathy' },
    ],
    extraFields: [
      { key: 'buddy',       label: 'Buddy',       type: 'text'   },
      { key: 'rival',       label: 'Rival',       type: 'text'   },
      { key: 'agenda',      label: 'Agenda',      type: 'text'   },
      { key: 'armor',       label: 'Armor Rating', type: 'number' },
      { key: 'cons_air',   label: 'Air',          type: 'number' },
      { key: 'cons_food',  label: 'Food',         type: 'number' },
      { key: 'cons_water', label: 'Water',        type: 'number' },
      { key: 'cons_power', label: 'Power',        type: 'number' },
    ],
    conditions: ['starving', 'dehydrated', 'exhausted', 'freezing'],
    systemSkills: [
      { key: 'sk_close_combat',  label: 'Close Combat',   attr: 'Strength' },
      { key: 'sk_heavy_mach',    label: 'Heavy Machinery',attr: 'Strength' },
      { key: 'sk_stamina',       label: 'Stamina',        attr: 'Strength' },
      { key: 'sk_ranged_combat', label: 'Ranged Combat',  attr: 'Agility'  },
      { key: 'sk_mobility',      label: 'Mobility',       attr: 'Agility'  },
      { key: 'sk_piloting',      label: 'Piloting',       attr: 'Agility'  },
      { key: 'sk_observation',   label: 'Observation',    attr: 'Wits'     },
      { key: 'sk_comtech',       label: 'Comtech',        attr: 'Wits'     },
      { key: 'sk_survival',      label: 'Survival',       attr: 'Wits'     },
      { key: 'sk_command',       label: 'Command',        attr: 'Empathy'  },
      { key: 'sk_manipulation',  label: 'Manipulation',   attr: 'Empathy'  },
      { key: 'sk_medical_aid',   label: 'Medical Aid',    attr: 'Empathy'  },
    ],
  },
  coriolis: {
    hasStress: false, hasSanity: false,
    usesXP: true, usesMilestone: false,
    hasDndBeyond: false, hasBuiltinSheet: true,
    hasMindPoints: true,
    hasRadiation: true,
    maxLevel: 5,
    sheetLabel: 'Character Sheet',
    coreStats: [
      { key: 'strength', label: 'Strength' }, { key: 'agility', label: 'Agility' },
      { key: 'wits',     label: 'Wits'     }, { key: 'empathy', label: 'Empathy' },
    ],
    extraFields: [
      { key: 'icon',             label: 'Icon', type: 'select',
        options: ['The Dancer','The Judge','The Messenger','The Merchant','The Mystic','The Poet','The Soldier','The Worker'] },
      { key: 'group_concept',    label: 'Group Concept',    type: 'text'   },
      { key: 'reputation',       label: 'Reputation',       type: 'number' },
      { key: 'personal_problem', label: 'Personal Problem', type: 'text'   },
      { key: 'face',             label: 'Face',             type: 'text'   },
      { key: 'clothing',         label: 'Clothing',         type: 'text'   },
      { key: 'buddy_1',          label: 'Relationship 1',   type: 'text'   },
      { key: 'buddy_2',          label: 'Relationship 2',   type: 'text'   },
      { key: 'buddy_3',          label: 'Relationship 3',   type: 'text'   },
      { key: 'buddy_4',          label: 'Relationship 4',   type: 'text'   },
      { key: 'trauma',           label: 'Trauma',           type: 'number' },
    ],
    systemSkills: [
      { key: 'sk_dexterity',   label: 'Dexterity',    attr: 'Agility', group: 'general'  },
      { key: 'sk_force',       label: 'Force',        attr: 'Strength',group: 'general'  },
      { key: 'sk_infiltration',label: 'Infiltration', attr: 'Agility', group: 'general'  },
      { key: 'sk_manipulation',label: 'Manipulation', attr: 'Empathy', group: 'general'  },
      { key: 'sk_melee',       label: 'Melee Combat', attr: 'Strength',group: 'general'  },
      { key: 'sk_observation', label: 'Observation',  attr: 'Wits',    group: 'general'  },
      { key: 'sk_ranged',      label: 'Ranged Combat',attr: 'Agility', group: 'general'  },
      { key: 'sk_survival',    label: 'Survival',     attr: 'Wits',    group: 'general'  },
      { key: 'sk_command',     label: 'Command',      attr: 'Empathy', group: 'advanced' },
      { key: 'sk_culture',     label: 'Culture',      attr: 'Empathy', group: 'advanced' },
      { key: 'sk_data_djinn',  label: 'Data Djinn',   attr: 'Wits',    group: 'advanced' },
      { key: 'sk_medicurgy',   label: 'Medicurgy',    attr: 'Wits',    group: 'advanced' },
      { key: 'sk_mystic',      label: 'Mystic Powers',attr: 'Empathy', group: 'advanced' },
      { key: 'sk_pilot',       label: 'Pilot',        attr: 'Agility', group: 'advanced' },
      { key: 'sk_science',     label: 'Science',      attr: 'Wits',    group: 'advanced' },
      { key: 'sk_technology',  label: 'Technology',   attr: 'Wits',    group: 'advanced' },
    ],
  },
  dune: {
    hasStress: false, hasSanity: false,
    usesXP: true, usesMilestone: false,
    hasDndBeyond: false, hasBuiltinSheet: true,
    hasDrives: true,
    maxLevel: 10,
    sheetLabel: 'Character Sheet',
    coreStats: [
      { key: 'bod', label: 'Body'    }, { key: 'agi', label: 'Agility' },
      { key: 'mnd', label: 'Mind'   }, { key: 'soc', label: 'Social'  },
      { key: 'spi', label: 'Spirit' },
    ],
    extraFields: [
      { key: 'house',             label: 'House',             type: 'text'   },
      { key: 'faction',           label: 'Faction',           type: 'text'   },
      { key: 'ambition',          label: 'Ambition',          type: 'text'   },
      { key: 'drive',             label: 'Drive',             type: 'text'   },
      { key: 'statement',         label: 'Statement',         type: 'text'   },
      { key: 'personality_traits',label: 'Personality Traits',type: 'text'   },
      { key: 'determination',     label: 'Determination Pts', type: 'number' },
      { key: 'assets',            label: 'Assets',            type: 'text'   },
    ],
    drives: ['duty', 'faith', 'justice', 'power', 'truth'],
    systemSkills: [
      { key: 'sk_battle',      label: 'Battle'      },
      { key: 'sk_communicate', label: 'Communicate' },
      { key: 'sk_discipline',  label: 'Discipline'  },
      { key: 'sk_move',        label: 'Move'        },
      { key: 'sk_understand',  label: 'Understand'  },
    ],
  },
  achtung: {
    hasStress: true, hasSanity: true,
    usesXP: true, usesMilestone: false,
    hasDndBeyond: false, hasBuiltinSheet: true,
    maxLevel: 10,
    sheetLabel: 'Character Sheet',
    coreStats: [
      { key: 'ach_agi',    label: 'Agility'     },
      { key: 'ach_brawn',  label: 'Brawn'       },
      { key: 'ach_coord',  label: 'Coordination'},
      { key: 'ach_insight',label: 'Insight'     },
      { key: 'ach_reason', label: 'Reason'      },
      { key: 'ach_will',   label: 'Will'        },
    ],
    extraFields: [
      { key: 'courage',        label: 'Courage',               type: 'number' },
      { key: 'fortune',        label: 'Fortune',               type: 'number' },
      { key: 'languages',      label: 'Languages',             type: 'text'   },
      { key: 'personal_truths',label: 'Personal Truths & Scars',type: 'text'  },
      { key: 'injuries',       label: 'Injuries',              type: 'text'   },
      { key: 'armour',         label: 'Armour',                type: 'text'   },
      { key: 'equipment_note', label: 'Equipment of Note',    type: 'textarea'},
    ],
    systemSkills: [
      { key: 'sk_academia',    label: 'Academia'    },
      { key: 'sk_athletics',   label: 'Athletics'   },
      { key: 'sk_engineering', label: 'Engineering' },
      { key: 'sk_fighting',    label: 'Fighting'    },
      { key: 'sk_medicine',    label: 'Medicine'    },
      { key: 'sk_observation', label: 'Observation' },
      { key: 'sk_persuasion',  label: 'Persuasion'  },
      { key: 'sk_resilience',  label: 'Resilience'  },
      { key: 'sk_stealth',     label: 'Stealth'     },
      { key: 'sk_survival',    label: 'Survival'    },
      { key: 'sk_tactics',     label: 'Tactics'     },
      { key: 'sk_vehicles',    label: 'Vehicles'    },
    ],
  },
  custom: {
    hasStress: true, hasSanity: true,
    usesXP: true, usesMilestone: false,
    hasDndBeyond: false, hasBuiltinSheet: true,
    maxLevel: 20,
    sheetLabel: 'Character Sheet',
    coreStats: [
      { key: 'str', label: 'STR' }, { key: 'dex', label: 'DEX' },
      { key: 'con', label: 'CON' }, { key: 'int', label: 'INT' },
      { key: 'wis', label: 'WIS' }, { key: 'cha', label: 'CHA' },
    ],
  },
}

const DEFAULTS = {
  hasStress: true, hasSanity: true,
  usesXP: true, usesMilestone: false,
  hasDndBeyond: false, hasBuiltinSheet: true,
  maxLevel: 20, sheetLabel: 'Character Sheet',
  coreStats: [
    { key: 'str', label: 'STR' }, { key: 'dex', label: 'DEX' },
    { key: 'con', label: 'CON' }, { key: 'int', label: 'INT' },
    { key: 'wis', label: 'WIS' }, { key: 'cha', label: 'CHA' },
  ],
}

export function useSystemFeatures() {
  const campaign = useCampaignStore()
  const features = computed(() => {
    const sys = campaign.activeCampaign?.system
    return SYSTEM_FEATURES[sys] ?? DEFAULTS
  })
  return {
    hasStress:       computed(() => features.value.hasStress),
    hasSanity:       computed(() => features.value.hasSanity),
    usesXP:          computed(() => features.value.usesXP),
    usesMilestone:   computed(() => features.value.usesMilestone),
    hasDndBeyond:    computed(() => features.value.hasDndBeyond),
    hasBuiltinSheet: computed(() => features.value.hasBuiltinSheet),
    hasMagicPoints:  computed(() => features.value.hasMagicPoints  ?? false),
    hasMindPoints:   computed(() => features.value.hasMindPoints   ?? false),
    hasConditions:   computed(() => features.value.hasConditions   ?? false),
    hasRadiation:    computed(() => features.value.hasRadiation    ?? false),
    hasDrives:       computed(() => features.value.hasDrives       ?? false),
    maxLevel:        computed(() => features.value.maxLevel),
    sheetLabel:      computed(() => features.value.sheetLabel),
    coreStats:       computed(() => features.value.coreStats       ?? DEFAULTS.coreStats),
    extraFields:     computed(() => features.value.extraFields     ?? []),
    systemSkills:    computed(() => features.value.systemSkills    ?? []),
    conditions:      computed(() => features.value.conditions      ?? []),
    drives:          computed(() => features.value.drives          ?? []),
  }
}
