import { computed } from 'vue'
import { useCampaignStore } from '@/stores/campaign'

export const COC_ERAS = [
  { key: '1920s',     label: '1920s Era',           hint: 'e.g. March 14, 1923' },
  { key: 'modern',    label: 'Modern Era',           hint: 'e.g. October 31, 2024' },
  { key: 'delta',     label: 'Delta Green',          hint: 'e.g. November 3, 2024' },
  { key: 'gaslight',  label: 'Victorian / Gaslight', hint: 'e.g. 12 April 1890' },
  { key: 'dark_ages', label: 'Dark Ages',            hint: 'e.g. Autumn 1217 AD' },
]

// Per-system feature flags — controls which mechanics are visible in the UI.
const SYSTEM_FEATURES = {
  dnd5e: {
    hasStress: false, hasSanity: false,
    usesXP: false, usesMilestone: true,
    hasDndBeyond: true, hasBuiltinSheet: false,
    maxLevel: 20,
    sheetLabel: 'D&D Beyond',
  },
  coc: {
    hasStress: false, hasSanity: true,
    usesXP: true, usesMilestone: false,
    hasDndBeyond: false, hasBuiltinSheet: true,
    hasMagicPoints: true,
    maxLevel: 10,
    sheetLabel: 'Investigator Sheet',
    coreStats: [
      { key: 'str',  label: 'STR',  help: 'Strength — raw physical power, melee attacks and carrying capacity. Max 90.' },
      { key: 'con',  label: 'CON',  help: 'Constitution — endurance. HP Max = (CON + SIZ) ÷ 10, rounded up.' },
      { key: 'siz',  label: 'SIZ',  help: 'Size — body mass. Also contributes to HP and damage bonus.' },
      { key: 'dex',  label: 'DEX',  help: 'Dexterity — agility and reaction speed. Dodge base = DEX × 2.' },
      { key: 'app',  label: 'APP',  help: 'Appearance — looks and first impressions. Used for social interactions.' },
      { key: 'edu',  label: 'EDU',  help: 'Education — knowledge. Determines skill point pool at character creation.' },
      { key: 'int',  label: 'INT',  help: 'Intelligence — reasoning and perception. Idea roll = INT × 5.' },
      { key: 'pow',  label: 'POW',  help: 'Power — willpower and spirit. Sanity starts at POW × 5; Magic Points = POW.' },
      { key: 'luck', label: 'Luck', help: 'Starting luck pool. Spend points to flip dice rolls or avoid misfortune.' },
    ],
    extraFields: [
      // Identity (shown in generic edit grid)
      { key: 'age',            label: 'Age',            type: 'number', help: 'Older investigators have more skills; younger ones have more skill points to spend.' },
      { key: 'birthplace',     label: 'Birthplace',     type: 'text' },
      { key: 'pronoun',        label: 'Pronoun',        type: 'text' },
      { key: 'residence',      label: 'Residence',      type: 'text' },
      // Wealth (shown in generic edit grid)
      { key: 'assets',         label: 'Assets',         type: 'text', help: 'Cash, property and valuables. Ties into Credit Rating for social situations.' },
      { key: 'spending_level', label: 'Spending Level', type: 'text', help: 'Lifestyle bracket: Poor, Average, Affluent, Wealthy. Determines what purchases are trivial.' },
      // Status (boolean — rendered in Status section)
      { key: 'major_wound',    label: 'Major Wound',        type: 'boolean', help: 'Took ≥ half max HP in a single hit. Must make a CON roll or fall unconscious. Healing takes weeks.' },
      { key: 'temp_insanity',  label: 'Temporary Insanity', type: 'boolean', help: 'Lost 5+ Sanity in one roll. Triggers a bout of madness (1d10 rounds or hours). Recovers naturally.' },
      { key: 'indef_insanity', label: 'Indefinite Insanity',type: 'boolean', help: 'Lost ≥ 1/5 max Sanity in one session. Requires therapy to recover. May develop a permanent phobia or mania.' },
      { key: 'unconscious',    label: 'Unconscious',        type: 'boolean', help: 'HP reached 0 or a major wound CON roll failed. Revive with First Aid.' },
      { key: 'dying',          label: 'Dying',              type: 'boolean', help: 'HP = 1 or 2. Will die in 1d6 rounds without successful First Aid.' },
      // Gear (textarea — handled via generic textarea loop)
      { key: 'gear',           label: 'Gear & Possessions', type: 'textarea' },
      // Backstory fields (section: 'backstory' — CoC-specific sections below skills)
      { key: 'story',                 label: 'My Story',                      type: 'textarea', section: 'backstory', help: 'The narrative of your investigator\'s life before this investigation.' },
      { key: 'personal_description',  label: 'Personal Description',          type: 'text',     section: 'backstory' },
      { key: 'traits',                label: 'Traits',                        type: 'text',     section: 'backstory', help: 'Mannerisms and personality quirks that define how others see you.' },
      { key: 'ideology_beliefs',      label: 'Ideology & Beliefs',            type: 'text',     section: 'backstory', help: 'What your investigator believes in — religion, politics, philosophy.' },
      { key: 'injuries_scars',        label: 'Injuries & Scars',              type: 'text',     section: 'backstory', help: 'Old wounds and the stories behind them.' },
      { key: 'significant_people',    label: 'Significant People',            type: 'text',     section: 'backstory', help: 'Who matters most, and why.' },
      { key: 'phobias_manias',        label: 'Phobias & Manias',              type: 'text',     section: 'backstory', help: 'Irrational fears or compulsions, possibly gained from SAN loss.' },
      { key: 'meaningful_locations',  label: 'Meaningful Locations',          type: 'text',     section: 'backstory', help: 'Places that hold special significance for your investigator.' },
      { key: 'arcane_tomes',          label: 'Arcane Tomes & Spells',         type: 'text',     section: 'backstory', help: 'Mythos tomes read; spells known. Each tome raises Cthulhu Mythos.' },
      { key: 'treasured_possessions', label: 'Treasured Possessions',         type: 'text',     section: 'backstory' },
      { key: 'strange_encounters',    label: 'Encounters with Strange Entities', type: 'text',  section: 'backstory', help: 'Brushes with the Mythos that left a mark.' },
      // Fellow Investigators (section: 'fellow' — CoC-specific section)
      { key: 'fellow_1_name',   label: 'Fellow 1 Char',   type: 'text', section: 'fellow' },
      { key: 'fellow_1_player', label: 'Fellow 1 Player', type: 'text', section: 'fellow' },
      { key: 'fellow_2_name',   label: 'Fellow 2 Char',   type: 'text', section: 'fellow' },
      { key: 'fellow_2_player', label: 'Fellow 2 Player', type: 'text', section: 'fellow' },
      { key: 'fellow_3_name',   label: 'Fellow 3 Char',   type: 'text', section: 'fellow' },
      { key: 'fellow_3_player', label: 'Fellow 3 Player', type: 'text', section: 'fellow' },
      { key: 'fellow_4_name',   label: 'Fellow 4 Char',   type: 'text', section: 'fellow' },
      { key: 'fellow_4_player', label: 'Fellow 4 Player', type: 'text', section: 'fellow' },
    ],
    systemSkills: [
      { key: 'sk_accounting',    label: 'Accounting',           base: 5  },
      { key: 'sk_anthropology',  label: 'Anthropology',         base: 1  },
      { key: 'sk_appraise',      label: 'Appraise',             base: 5  },
      { key: 'sk_archaeology',   label: 'Archaeology',          base: 1  },
      { key: 'sk_art',           label: 'Art/Craft',            base: 5  },
      { key: 'sk_charm',         label: 'Charm',                base: 15 },
      { key: 'sk_climb',         label: 'Climb',                base: 20 },
      { key: 'sk_credit',        label: 'Credit Rating',        base: 0  },
      { key: 'sk_cthulhu',       label: 'Cthulhu Mythos',       base: 0  },
      { key: 'sk_disguise',      label: 'Disguise',             base: 5  },
      { key: 'sk_dodge',         label: 'Dodge',                base: 0, note: 'DEX×2' },
      { key: 'sk_drive',         label: 'Drive Auto',           base: 20 },
      { key: 'sk_elec_repair',   label: 'Elec. Repair',         base: 10 },
      { key: 'sk_fast_talk',     label: 'Fast Talk',            base: 5  },
      { key: 'sk_fighting',      label: 'Fighting (Brawl)',     base: 25 },
      { key: 'sk_firearms_h',    label: 'Firearms (Handgun)',   base: 20 },
      { key: 'sk_firearms_r',    label: 'Firearms (Rifle/SG)',  base: 25 },
      { key: 'sk_first_aid',     label: 'First Aid',            base: 30 },
      { key: 'sk_history',       label: 'History',              base: 5  },
      { key: 'sk_intimidate',    label: 'Intimidate',           base: 15 },
      { key: 'sk_jump',          label: 'Jump',                 base: 20 },
      { key: 'sk_language',      label: 'Language (Other)',     base: 1  },
      { key: 'sk_law',           label: 'Law',                  base: 5  },
      { key: 'sk_library',       label: 'Library Use',          base: 20 },
      { key: 'sk_listen',        label: 'Listen',               base: 20 },
      { key: 'sk_locksmith',     label: 'Locksmith',            base: 1  },
      { key: 'sk_mech_repair',   label: 'Mech. Repair',         base: 10 },
      { key: 'sk_medicine',      label: 'Medicine',             base: 1  },
      { key: 'sk_natural',       label: 'Natural World',        base: 10 },
      { key: 'sk_navigate',      label: 'Navigate',             base: 10 },
      { key: 'sk_occult',        label: 'Occult',               base: 5  },
      { key: 'sk_operate',       label: 'Op. Hvy. Mach.',       base: 1  },
      { key: 'sk_persuade',      label: 'Persuade',             base: 10 },
      { key: 'sk_pilot',         label: 'Pilot',                base: 1  },
      { key: 'sk_psychology',    label: 'Psychology',           base: 10 },
      { key: 'sk_psychoanalysis',label: 'Psychoanalysis',       base: 1  },
      { key: 'sk_ride',          label: 'Ride',                 base: 5  },
      { key: 'sk_science',       label: 'Science',              base: 1  },
      { key: 'sk_sleight',       label: 'Sleight of Hand',      base: 10 },
      { key: 'sk_spot',          label: 'Spot Hidden',          base: 25 },
      { key: 'sk_stealth',       label: 'Stealth',              base: 20 },
      { key: 'sk_survival',      label: 'Survival',             base: 10 },
      { key: 'sk_swim',          label: 'Swim',                 base: 20 },
      { key: 'sk_throw',         label: 'Throw',                base: 20 },
      { key: 'sk_track',         label: 'Track',                base: 10 },
    ],
  },
  alien: {
    hasStress: true, hasSanity: false,
    usesXP: true, usesMilestone: false,
    hasDndBeyond: false, hasBuiltinSheet: true,
    hasConditions: true,
    hasRadiation: true,
    maxLevel: 5,
    sheetLabel: 'Character Sheet',
    coreStats: [
      { key: 'strength', label: 'Strength', help: 'Physical power. Used for Close Combat, Heavy Machinery and Stamina skills.' },
      { key: 'agility',  label: 'Agility',  help: 'Speed and nimbleness. Used for Ranged Combat, Mobility and Piloting.' },
      { key: 'wits',     label: 'Wits',     help: 'Alertness and intelligence. Used for Observation, Comtech and Survival.' },
      { key: 'empathy',  label: 'Empathy',  help: 'Social awareness. Used for Command, Manipulation and Medical Aid.' },
    ],
    extraFields: [
      { key: 'buddy',          label: 'Buddy',         type: 'text',   help: 'The one crew member you trust most. Protecting them reduces Stress.' },
      { key: 'rival',          label: 'Rival',         type: 'text',   help: 'The crew member you resent. Being near them increases tension.' },
      { key: 'agenda',         label: 'Agenda',        type: 'text',   help: 'Your personal secret mission — unknown to the rest of the crew.' },
      { key: 'armor',          label: 'Armor Rating',  type: 'number', help: 'Reduces incoming damage by this amount before HP is lost.' },
      { key: 'signature_item', label: 'Signature Item',type: 'text',   help: 'A key piece of gear that defines your character. Can be pushed for extra effect.' },
      { key: 'encumbrance',    label: 'Encumbrance',   type: 'number', help: 'Items carried beyond your Strength score impose a –1 penalty per excess item.' },
      { key: 'tiny_items',     label: 'Tiny Items',     type: 'textarea', help: 'Small items that do not count toward encumbrance (ammo, med-kits, data discs, etc.).' },
      { key: 'cons_air',   label: 'Air',          type: 'number' },
      { key: 'cons_food',  label: 'Food',         type: 'number' },
      { key: 'cons_water', label: 'Water',        type: 'number' },
      { key: 'cons_power', label: 'Power',        type: 'number' },
    ],
    conditions: ['starving', 'dehydrated', 'exhausted', 'freezing'],
    systemSkills: [
      { key: 'sk_close_combat',  label: 'Close Combat',   attr: 'Strength' },
      { key: 'sk_heavy_mach',    label: 'Heavy Machinery',attr: 'Strength' },
      { key: 'sk_stamina',       label: 'Stamina',        attr: 'Strength' },
      { key: 'sk_ranged_combat', label: 'Ranged Combat',  attr: 'Agility'  },
      { key: 'sk_mobility',      label: 'Mobility',       attr: 'Agility'  },
      { key: 'sk_piloting',      label: 'Piloting',       attr: 'Agility'  },
      { key: 'sk_observation',   label: 'Observation',    attr: 'Wits'     },
      { key: 'sk_comtech',       label: 'Comtech',        attr: 'Wits'     },
      { key: 'sk_survival',      label: 'Survival',       attr: 'Wits'     },
      { key: 'sk_command',       label: 'Command',        attr: 'Empathy'  },
      { key: 'sk_manipulation',  label: 'Manipulation',   attr: 'Empathy'  },
      { key: 'sk_medical_aid',   label: 'Medical Aid',    attr: 'Empathy'  },
    ],
  },
  coriolis: {
    hasStress: false, hasSanity: false,
    usesXP: true, usesMilestone: false,
    hasDndBeyond: false, hasBuiltinSheet: true,
    hasMindPoints: true,
    hasRadiation: true,
    maxLevel: 5,
    sheetLabel: 'Character Sheet',
    coreStats: [
      { key: 'strength', label: 'Strength', help: 'Physical power. Used for Force and Melee Combat. Contributes to HP Max (STR + AGL).' },
      { key: 'agility',  label: 'Agility',  help: 'Speed and coordination. Used for Dexterity, Infiltration, Ranged Combat and Pilot. Contributes to HP Max.' },
      { key: 'wits',     label: 'Wits',     help: 'Alertness and intellect. Used for Observation, Data Djinn, Medicurgy, Science and Technology. Contributes to Mind Points.' },
      { key: 'empathy',  label: 'Empathy',  help: 'Social and spiritual insight. Used for Manipulation, Command, Culture and Mystic Powers. Contributes to Mind Points.' },
    ],
    extraFields: [
      { key: 'icon',             label: 'Icon', type: 'select', help: 'Your patron Icon — shapes your background talents and spiritual allegiance.',
        options: ['The Dancer','The Judge','The Messenger','The Merchant','The Mystic','The Poet','The Soldier','The Worker'] },
      { key: 'group_concept',    label: 'Group Concept',    type: 'text',   help: 'One sentence describing what your crew does together.' },
      { key: 'reputation',       label: 'Reputation',       type: 'number', help: 'Your standing in the Third Horizon. Spend to call in favours; lose it through infamy.' },
      { key: 'personal_problem', label: 'Personal Problem', type: 'text',   help: 'An ongoing flaw or complication that drives your character\'s story arc.' },
      { key: 'face',             label: 'Face',             type: 'text',   help: 'Distinctive facial features or expressions others remember you by.' },
      { key: 'clothing',         label: 'Clothing',         type: 'text',   help: 'Your typical dress — reflects status, faction and personal style.' },
      { key: 'buddy_1',          label: 'Relationship 1',   type: 'text',   help: 'Name of a crew member you have a bond or history with.' },
      { key: 'buddy_2',          label: 'Relationship 2',   type: 'text',   help: 'Name of a crew member you have a bond or history with.' },
      { key: 'buddy_3',          label: 'Relationship 3',   type: 'text',   help: 'Name of a crew member you have a bond or history with.' },
      { key: 'buddy_4',          label: 'Relationship 4',   type: 'text',   help: 'Name of a crew member you have a bond or history with.' },
      { key: 'trauma',           label: 'Trauma',           type: 'number', help: 'Permanent trauma points from losing all Mind Points. Each point is a lasting mental scar.' },
      { key: 'tiny_items',       label: 'Tiny Items',       type: 'textarea', help: 'Small items that do not count toward encumbrance (ammo, med-kits, data discs, etc.).' },
    ],
    systemSkills: [
      { key: 'sk_dexterity',   label: 'Dexterity',    attr: 'Agility', group: 'general'  },
      { key: 'sk_force',       label: 'Force',        attr: 'Strength',group: 'general'  },
      { key: 'sk_infiltration',label: 'Infiltration', attr: 'Agility', group: 'general'  },
      { key: 'sk_manipulation',label: 'Manipulation', attr: 'Empathy', group: 'general'  },
      { key: 'sk_melee',       label: 'Melee Combat', attr: 'Strength',group: 'general'  },
      { key: 'sk_observation', label: 'Observation',  attr: 'Wits',    group: 'general'  },
      { key: 'sk_ranged',      label: 'Ranged Combat',attr: 'Agility', group: 'general'  },
      { key: 'sk_survival',    label: 'Survival',     attr: 'Wits',    group: 'general'  },
      { key: 'sk_command',     label: 'Command',      attr: 'Empathy', group: 'advanced' },
      { key: 'sk_culture',     label: 'Culture',      attr: 'Empathy', group: 'advanced' },
      { key: 'sk_data_djinn',  label: 'Data Djinn',   attr: 'Wits',    group: 'advanced' },
      { key: 'sk_medicurgy',   label: 'Medicurgy',    attr: 'Wits',    group: 'advanced' },
      { key: 'sk_mystic',      label: 'Mystic Powers',attr: 'Empathy', group: 'advanced' },
      { key: 'sk_pilot',       label: 'Pilot',        attr: 'Agility', group: 'advanced' },
      { key: 'sk_science',     label: 'Science',      attr: 'Wits',    group: 'advanced' },
      { key: 'sk_technology',  label: 'Technology',   attr: 'Wits',    group: 'advanced' },
    ],
  },
  dune: {
    hasStress: false, hasSanity: false,
    usesXP: true, usesMilestone: false,
    hasDndBeyond: false, hasBuiltinSheet: true,
    hasDrives: true,
    maxLevel: 10,
    sheetLabel: 'Character Sheet',
    coreStats: [
      { key: 'bod', label: 'Body',    help: 'Physical strength and endurance. Used for violence, athletics and surviving harsh conditions.' },
      { key: 'agi', label: 'Agility', help: 'Speed and reflexes. Used for stealth, ranged combat and feats of dexterity.' },
      { key: 'mnd', label: 'Mind',    help: 'Intelligence and perception. Used for technology, scheming and resisting deception.' },
      { key: 'soc', label: 'Social',  help: 'Charisma and status. Used for leadership, persuasion and political influence.' },
      { key: 'spi', label: 'Spirit',  help: 'Willpower and faith. Used for composure, prescience and resisting mental trauma.' },
    ],
    extraFields: [
      { key: 'house',             label: 'House',             type: 'text',   help: 'The Great or Minor House your character serves or belongs to.' },
      { key: 'faction',           label: 'Faction',           type: 'text',   help: 'Guild, Bene Gesserit, Fremen, or other organisation you are affiliated with.' },
      { key: 'ambition',          label: 'Ambition',          type: 'text',   help: 'Your long-term personal goal. Achieving it earns bonus XP.' },
      { key: 'drive',             label: 'Drive',             type: 'text',   help: 'The core value that motivates you (Duty, Faith, Justice, Power or Truth).' },
      { key: 'statement',         label: 'Statement',         type: 'text',   help: 'A short declaration of belief tied to your Drive. Guides roleplaying decisions.' },
      { key: 'personality_traits',label: 'Personality Traits',type: 'text',   help: 'Recurring behaviours and quirks that define how your character acts under pressure.' },
      { key: 'determination',     label: 'Determination Pts', type: 'number', help: 'Spendable pool for bonus dice or narrative effects. Refreshes each session.' },
      { key: 'assets',            label: 'Assets',            type: 'text',   help: 'Wealth, property and resources available to your character.' },
    ],
    drives: ['duty', 'faith', 'justice', 'power', 'truth'],
    systemSkills: [
      { key: 'sk_battle',      label: 'Battle',      attr: 'Body',    help: 'Violence, weapons and physical combat.' },
      { key: 'sk_communicate', label: 'Communicate', attr: 'Social',  help: 'Persuasion, deception, oratory and reading people.' },
      { key: 'sk_discipline',  label: 'Discipline',  attr: 'Spirit',  help: 'Composure under pressure, resisting temptation and mental fortitude.' },
      { key: 'sk_move',        label: 'Move',        attr: 'Agility', help: 'Athletics, stealth, piloting and physical feats.' },
      { key: 'sk_understand',  label: 'Understand',  attr: 'Mind',    help: 'Technology, lore, scheming and interpreting information.' },
    ],
  },
  achtung: {
    hasStress: true, hasSanity: true,
    usesXP: true, usesMilestone: false,
    hasDndBeyond: false, hasBuiltinSheet: true,
    maxLevel: 10,
    sheetLabel: 'Character Sheet',
    coreStats: [
      { key: 'ach_agi',    label: 'Agility',      help: 'Speed and evasion. Used for Athletics, Stealth and Vehicles.' },
      { key: 'ach_brawn',  label: 'Brawn',        help: 'Raw physical strength. Used for Fighting and heavy lifting.' },
      { key: 'ach_coord',  label: 'Coordination', help: 'Precision and fine motor control. Used for Engineering and ranged attacks.' },
      { key: 'ach_insight',label: 'Insight',      help: 'Intuition and Mythos awareness. Used for Observation and sensing the uncanny.' },
      { key: 'ach_reason', label: 'Reason',       help: 'Intelligence and analysis. Used for Academia, Engineering and Medicine.' },
      { key: 'ach_will',   label: 'Will',         help: 'Mental fortitude. Determines Stress capacity and resists Sanity loss.' },
    ],
    extraFields: [
      { key: 'characteristic', label: 'Characteristic',         type: 'text',   help: 'A defining trait, flaw or ideal that sets your character apart.' },
      { key: 'courage',        label: 'Courage',                type: 'number', help: 'Spend to reroll dice or resist fear. Refreshes at the start of each session.' },
      { key: 'fortune',        label: 'Fortune',                type: 'number', help: 'Spend to avoid death or gain a lucky break. Hard to recover — use sparingly.' },
      { key: 'languages',      label: 'Languages',              type: 'text',   help: 'Languages your character speaks. May grant bonus dice for relevant communication tasks.' },
      { key: 'personal_truths',label: 'Personal Truths & Scars',type: 'text',   help: 'Events that shaped your character. Can be invoked for bonus dice when relevant.' },
      { key: 'injuries',       label: 'Injuries',               type: 'text',   help: 'Current wounds and their severity. Two serious injuries render you incapacitated.' },
      { key: 'armour',         label: 'Armour',                 type: 'text',   help: 'Armour rating reduces damage received. Note type and rating here.' },
      { key: 'equipment_note', label: 'Equipment of Note',      type: 'textarea' },
      { key: 'biography',      label: 'Biography',              type: 'textarea', section: 'achtung' },
    ],
    systemSkills: [
      { key: 'sk_academia',    label: 'Academia',    attr: 'Reason',      help: 'Occult knowledge, history and academic research.' },
      { key: 'sk_athletics',   label: 'Athletics',   attr: 'Agility',     help: 'Running, climbing, jumping and feats of physical exertion.' },
      { key: 'sk_engineering', label: 'Engineering', attr: 'Coordination',help: 'Building, repairing and operating mechanical or electrical devices.' },
      { key: 'sk_fighting',    label: 'Fighting',    attr: 'Brawn',       help: 'Melee combat, brawling and close-quarters attacks.' },
      { key: 'sk_medicine',    label: 'Medicine',    attr: 'Reason',      help: 'First aid, surgery and treating injuries or disease.' },
      { key: 'sk_observation', label: 'Observation', attr: 'Insight',     help: 'Noticing details, detecting lies and sensing danger.' },
      { key: 'sk_persuasion',  label: 'Persuasion',  attr: 'Insight',     help: 'Convincing, inspiring or intimidating others.' },
      { key: 'sk_resilience',  label: 'Resilience',  attr: 'Brawn',       help: 'Enduring hardship, resisting poison/disease and recovering from stress.' },
      { key: 'sk_stealth',     label: 'Stealth',     attr: 'Agility',     help: 'Moving silently, hiding and avoiding detection.' },
      { key: 'sk_survival',    label: 'Survival',    attr: 'Agility',     help: 'Navigating wilderness, foraging, tracking and avoiding environmental hazards.' },
      { key: 'sk_tactics',     label: 'Tactics',     attr: 'Reason',      help: 'Planning, coordinating allies and understanding battlefield situations.' },
      { key: 'sk_vehicles',    label: 'Vehicles',    attr: 'Coordination',help: 'Operating cars, trucks, tanks and other powered vehicles.' },
    ],
  },
  custom: {
    hasStress: true, hasSanity: true,
    usesXP: true, usesMilestone: false,
    hasDndBeyond: false, hasBuiltinSheet: true,
    maxLevel: 20,
    sheetLabel: 'Character Sheet',
    coreStats: [
      { key: 'str', label: 'STR', help: 'Strength — physical power, melee attacks and carrying capacity.' },
      { key: 'dex', label: 'DEX', help: 'Dexterity — agility, reflexes and ranged attacks.' },
      { key: 'con', label: 'CON', help: 'Constitution — endurance and resistance to damage.' },
      { key: 'int', label: 'INT', help: 'Intelligence — knowledge, memory and reasoning.' },
      { key: 'wis', label: 'WIS', help: 'Wisdom — perception, insight and willpower.' },
      { key: 'cha', label: 'CHA', help: 'Charisma — presence, persuasion and leadership.' },
    ],
  },
}

const DEFAULTS = {
  hasStress: true, hasSanity: true,
  usesXP: true, usesMilestone: false,
  hasDndBeyond: false, hasBuiltinSheet: true,
  maxLevel: 20, sheetLabel: 'Character Sheet',
  coreStats: [
    { key: 'str', label: 'STR', help: 'Strength — physical power, melee attacks and carrying capacity.' },
    { key: 'dex', label: 'DEX', help: 'Dexterity — agility, reflexes and ranged attacks.' },
    { key: 'con', label: 'CON', help: 'Constitution — endurance and resistance to damage.' },
    { key: 'int', label: 'INT', help: 'Intelligence — knowledge, memory and reasoning.' },
    { key: 'wis', label: 'WIS', help: 'Wisdom — perception, insight and willpower.' },
    { key: 'cha', label: 'CHA', help: 'Charisma — presence, persuasion and leadership.' },
  ],
}

export function useSystemFeatures() {
  const campaign = useCampaignStore()
  const features = computed(() => {
    const sys = campaign.activeCampaign?.system
    return SYSTEM_FEATURES[sys] ?? DEFAULTS
  })
  const cocEra = computed(() => {
    if (activeSys.value !== 'coc') return null
    return campaign.activeCampaign?.coc_era || '1920s'
  })
  const cocEraLabel = computed(() => {
    if (!cocEra.value) return ''
    return COC_ERAS.find(e => e.key === cocEra.value)?.label || '1920s Era'
  })

  return {
    hasStress:       computed(() => features.value.hasStress),
    hasSanity:       computed(() => features.value.hasSanity),
    usesXP:          computed(() => features.value.usesXP),
    usesMilestone:   computed(() => features.value.usesMilestone),
    hasDndBeyond:    computed(() => features.value.hasDndBeyond),
    hasBuiltinSheet: computed(() => features.value.hasBuiltinSheet),
    hasMagicPoints:  computed(() => features.value.hasMagicPoints  ?? false),
    hasMindPoints:   computed(() => features.value.hasMindPoints   ?? false),
    hasConditions:   computed(() => features.value.hasConditions   ?? false),
    hasRadiation:    computed(() => features.value.hasRadiation    ?? false),
    hasDrives:       computed(() => features.value.hasDrives       ?? false),
    maxLevel:        computed(() => features.value.maxLevel),
    sheetLabel:      computed(() => features.value.sheetLabel),
    coreStats:       computed(() => features.value.coreStats       ?? DEFAULTS.coreStats),
    extraFields:     computed(() => features.value.extraFields     ?? []),
    systemSkills:    computed(() => features.value.systemSkills    ?? []),
    conditions:      computed(() => features.value.conditions      ?? []),
    drives:          computed(() => features.value.drives          ?? []),
    cocEra,
    cocEraLabel,
  }
}
